name: finans_kocu
description: AI-powered personal finance coach with Supabase backend.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^13.2.0
  supabase_flutter: ^2.5.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.4.0
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.9
  http: ^1.2.0
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
